pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220221140901/test_queue_pause_from/main
  name: queue
queue_rules:
- conditions:
  - check-success=continuous-integration/fake-ci
  name: default
