pull_request_rules:
- actions:
    queue:
      name: urgent
  conditions:
  - base=20220225145751/test_queue_is_paused/main
  - label=queue-urgent
  name: Merge priority high
- actions:
    queue:
      name: default
  conditions:
  - base=20220225145751/test_queue_is_paused/main
  - label=queue
  name: Merge default
- actions:
    queue:
      name: low-priority
  conditions:
  - base=20220225145751/test_queue_is_paused/main
  - label=queue-low
  name: Merge low
queue_rules:
- conditions:
  - status-success=continuous-integration/fast-ci
  name: urgent
- conditions:
  - status-success=continuous-integration/slow-ci
  name: default
- conditions:
  - status-success=continuous-integration/slow-ci
  name: low-priority
