pull_request_rules:
- actions:
    review:
      message: Thank you {{hello}}
      type: REQUEST_CHANGES
  conditions:
  - base=20240126000212/test_review_template_attribute_error/main
  - '#changes-requested-reviews-by=0'
  name: review
