pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220331124239/test_queue_merge_timeout_without_unqueuing/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- allow_inplace_checks: false
  checks_timeout: 10 m
  conditions:
  - check-success=continuous-integration/fake-ci
  name: default
