pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220405082142/test_queue_ci_timeout_draft_pr/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- allow_inplace_checks: false
  conditions:
  - check-success=continuous-integration/fake-ci
  name: default
