pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220324164009/test_queue_ci_timeout_draft_pr/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- allow_inplace_checks: false
  checks_timeout: 10 m
  conditions:
  - check-success=continuous-integration/fake-ci
  name: default
