pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- conditions:
  - check-success=continuous-integration/fake-ci
  name: foo
